from datetime import datetime, date
import random


def get_random_videos():
    all_videos = [
        {"title": "HYDE - MAD QUALIA (Japanese Version)", "video_id": "tTJxOamTkQg"},
        {"title": "SOCIAL VIRUS", "video_id": "u0qRa42JTPI"},
        {"title": "HYDE-6or9", "video_id": "_5lv1i0hJ84"},
        {"title": "HYDE-PANDORA", "video_id": "u4B7-5PKtAU"},
        {"title": "HYDE - 「FINAL PIECE」 MUSIC VIDEO", "video_id": "eh9aNuBfuCs"},
        {"title": "HYDE-NOSTALGIC", "video_id": "4DC_yRt14NM"},
        {"title": "HYDE-DEFEAT", "video_id": "fWTRBsNHzco"},
        {"title": "HYDE - LET IT OUT", "video_id": "trTK2hTBbDQ"},
        {"title": "HYDE - INTERPLAY", "video_id": "C9MfKdZ3xI8"},
        {"title": "HYDE - BELIEVING IN MYSELF", "video_id": "TAip5uMmdPw"},
        {"title": "HYDE - MAD QUALIA (English Version)", "video_id": "f1t3Za-o_lA"},
        {"title": "HYDE feat. YOSHIKI - ZIPANG（Japanese Version）", "video_id": "_wKq_C_LzM0"},
        {"title": "HYDE - FAKE DIVINE", "video_id": "zuG_pQ2GeHw"},
        {"title": "HYDE - 「AFTER LIGHT」 Music Video", "video_id": "pcSjLP0erjQ"},
        {"title": "HYDE - 「WHO’S GONNA SAVE US」Music Video", "video_id": "XMA_L5a5BKY"},
        {"title": "HYDE - HELLO", "video_id": "NMx6KGjGe2A"},
        {"title": "HYDE - SEASON’S CALL", "video_id": "6upBl-CIK9c"},
        {"title": "HYDE - HORIZON", "video_id": "7WtDufV5r7A"},
        {"title": "HYDE - evergreen", "video_id": "_NPjc-UCYtI"},
        {"title": "HYDE - SHALLOW SLEEP", "video_id": "onGF1y0IZDw"},
        {"title": "HYDE - Angel's tale", "video_id": "JoGRCdgK9Bk"},
        {"title": "HYDE - COUNTDOWN", "video_id": "xaL4YWiDjKY"},
        {"title": "HYDE - THE CAPE OF STORMS", "video_id": "ZHQpBCao_5k"},
        {"title": "LAST SONG", "video_id": "MoABRyCy3LY"},
        {"title": "HALLOWEEN PARTY Music Video Full Ver.【HALLOWEEN JUNKY ORCHESTRA】", "video_id": "7FMQrqFiTag"},
        {"title": "VAMPS - CALLING", "video_id": "TFaO4zdO9QE"},
        {"title": "VAMPS - VAMPIRE'S LOVE", "video_id": "8ZtO_px24go"},
        {"title": "VAMPS - VAMPIRE'S LOVE　- Japanese Version -", "video_id": "J0IfTazsnbU"},
        {"title": "VAMPS - GET AWAY", "video_id": "AxEpRdesqrE"},
        {"title": "VAMPS - THE JOLLY ROGER", "video_id": "AV9UKkT9eLw"},
        {"title": "VAMPS - REPLAY", "video_id": "379sKNqnkZo"},
        {"title": "VAMPS - WORLD'S END'", "video_id": "asbbg40HupM"},
        {"title": "VAMPS - AHEAD", "video_id": "N4WRxrL-6dw"},
        {"title": "VAMPS - MEMORIES", "video_id": "6njSwGjkX4g"},
        {"title": "VAMPS - ANGEL TRIP", "video_id": "nH39SeeziBA"},
        {"title": "VAMPS - DEVIL SIDE", "video_id": "ACeYT7bLEZo"},
        {"title": "VAMPS - SWEET DREAMS", "video_id": "UT6s6pmOE-c"},
        {"title": "VAMPS - EVANESCENT", "video_id": "eCcHbdYeEWQ"},
        {"title": "VAMPS - I GOTTA KICK START NOW", "video_id": "W31MC6-P4pg"},
        {"title": "VAMPS - LOVE ADDICT", "video_id": "O4DmBpFatmI"},
        {"title": "L'Arc～en～Ciel「YOU GOTTA RUN」-Music Clip-", "video_id": "6zMB4Q258tw"},
        {"title": "L'Arc～en～Ciel「FOREVER」-Music Clip-", "video_id": "jVlezpAcRRo"},
        {"title": "L'Arc～en～Ciel「ミライ」-Music Clip-", "video_id": "UBEoZ-eTa-o"},
        {"title": "L'Arc～en～Ciel「Don't be Afraid」-Music Clip-", "video_id": "1kWPVz9d1OA"},
        {"title": "L'Arc～en～Ciel「Wings Flap」-Music Clip-", "video_id": "egNF5eDEKow"},
        {"title": "L'Arc～en～Ciel「CHASE」-Music Clip-", "video_id": "z4PVhhy-_fM"},
        {"title": "L'Arc～en～Ciel「X X X」-Music Clip-", "video_id": "-HrxRpaou3A"},
        {"title": "L'Arc～en～Ciel「GOOD LUCK MY WAY」-Music Clip-", "video_id": "lpUKpyUi7wc"},
        {"title": "BLESS", "video_id": "mEiWzMzwzms"},
        {"title": "NEXUS 4", "video_id": "3YZE4kjmYK8"},
        {"title": "SHINE", "video_id": "QBpxlwauo3w"},
        {"title": "L'Arc～en～Ciel「DRINK IT DOWN」-Music Clip-", "video_id": "aY2UcYex3zY"},
        {"title": "Hurry Xmas", "video_id": "16712yfqGjY"},
        {"title": "L'Arc～en～Ciel「DAYBREAK'S BELL」-Music Clip-", "video_id": "VUOgmg0RXrE"},
        {"title": "L'Arc～en～Ciel「MY HEART DRAWS A DREAM」-Music Clip-", "video_id": "Clok-EGLfMA"},
        {"title": "L'Arc～en～Ciel「SEVENTH HEAVEN」-Music Clip-", "video_id": "H_UirgLIyt0"},
        {"title": "L'Arc～en～Ciel「Link」-Music Clip-", "video_id": "qmFTnudzlyI"},
        {"title": "L'Arc～en～Ciel「叙情詩」-Music Clip-", "video_id": "fTzVMr1_oIA"},
        {"title": "L'Arc～en～Ciel「New World」-Music Clip-", "video_id": "rCNvayKkpYI"},
        {"title": "L'Arc～en～Ciel「Killing Me」-Music Clip-", "video_id": "vvuQI93Am6Y"},
        {"title": "L'Arc～en～Ciel「自由への招待」-Music Clip-", "video_id": "NNm0LsGzIw0"},
        {"title": "L'Arc～en～Ciel「瞳の住人」-Music Clip-", "video_id": "Ssd111jVg2c"},
        {"title": "L'Arc～en～Ciel「READY STEADY GO」-Music Clip-", "video_id": "NZdjDUjzUiQ"},
        {"title": "L'Arc～en～Ciel「Spirit dreams inside-another dream-」-Music Clip-", "video_id": "LIor2p1COpg"},
        {"title": "L'Arc～en～Ciel「Anemone」-Music Clip-", "video_id": "dbBSQNfcqAI"},
        {"title": "L'Arc～en～Ciel「CHASE」-Music Clip-", "video_id": "z4PVhhy-_fM"},
        {"title": "L'Arc～en～Ciel「X X X」-Music Clip-", "video_id": "-HrxRpaou3A"},
        {"title": "L'Arc～en～Ciel「STAY AWAY」-Music Clip-", "video_id": "Dwj8qNrv1kI"},
        {"title": "L'Arc～en～Ciel「finale」-Music Clip-", "video_id": "G3okxKLNFVI"},
        {"title": "L'Arc～en～Ciel「NEO UNIVERSE」-Music Clip-", "video_id": "l_1-ZF6adRk"},
        {"title": "L'Arc～en～Ciel「LOVE FLIES」-Music Clip-", "video_id": "ZSBjfXe30p4"},
        {"title": "L'Arc～en～Ciel「Driver's High」-Music Clip-", "video_id": "bzuuxp7dsxQ"},
        {"title": "L'Arc～en～Ciel「Pieces」-Music Clip-", "video_id": "32b1bIz-hJE"},
        {"title": "L'Arc～en～Ciel「HEAVEN'S DRIVE」-Music Clip-", "video_id": "5gfWj9vMykw"},
        {"title": "L'Arc～en～Ciel「forbidden lover」-Music Clip-", "video_id": "KRO-H2Zw55s"},
        {"title": "L'Arc～en～Ciel「snow drop」-Music Clip-", "video_id": "IIoKENOaSOY"},
        {"title": "L'Arc～en～Ciel「浸食 -lose control-」-Music Clip-", "video_id": "w_AvHKcMqH4"},
        {"title": "L'Arc～en～Ciel「花葬」-Music Clip-", "video_id": "_erGU8VYKuE"},
        {"title": "L'Arc～en～Ciel「HONEY」-Music Clip-", "video_id": "WmM-KTcG3QY"},
        {"title": "L'Arc～en～Ciel「DIVE TO BLUE」-Music Clip-", "video_id": "l7LM_lZ91nk"},
        {"title": "L'Arc～en～Ciel「winter fall」-Music Clip-", "video_id": "TaNlrxTlIfM"},
        {"title": "L'Arc～en～Ciel「虹」-Music Clip-", "video_id": "G9yOkP1cNRY"},
        {"title": "L'Arc～en～Ciel「Lies and Truth」-Music Clip-", "video_id": "1qTW2NYO-2A"},
        {"title": "L'Arc～en～Ciel「flower」-Music Clip-", "video_id": "Tj4aN-JxA7M"},
        {"title": "L'Arc～en～Ciel「風にきえないで」-Music Clip-", "video_id": "cO-_vJMlJl4"},
        {"title": "L'Arc～en～Ciel「夏の憂鬱 [time to say good-bye]」-Music Clip-", "video_id": "u_9iwL8UBec"},
        {"title": "L'Arc～en～Ciel「and She Said」-Music Clip-", "video_id": "9T81-WSXyRA"},
        {"title": "L'Arc～en～Ciel「Vivid Colors」-Music Clip-", "video_id": "ZUaPim9C2cc"},
        {"title": "L'Arc～en～Ciel「瞳に映るもの」-Music Clip-", "video_id": "C-YbwaPN9lM"},
        {"title": "L'Arc～en～Ciel「風の行方」-Music Clip-", "video_id": "Yqs06uBu4IQ"},
        {"title": "L'Arc～en～Ciel「Blurry Eyes」-Music Clip-", "video_id": "RaV8KtB2QTM"},
        {"title": "L'Arc～en～Ciel「眠りによせて」-Music Clip-", "video_id": "M6d9P04FijQ"},
        {"title": "L'Arc～en～Ciel「As if in a dream」-Music Clip-", "video_id": "QELGuNmyqs8"},
        {"title": "L'Arc～en～Ciel「Floods of tears」-Music Clip-", "video_id": "Nt0S_5tPFLY"},
        {"title": "L'Arc～en～Ciel「Dune」-Music Clip-", "video_id": "ZiV0ZuYCzkY"},
    ]
    today_str = date.today().strftime('%Y%m%d')
    seed_value = int(today_str)
    random.seed(seed_value)
    if len(all_videos) >= 6:
        selected_videos = random.sample(all_videos, 6)
    else:
        selected_videos = all_videos
    # selected_videos = all_videos
    return selected_videos